apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jamesmurphyx-net-tls
spec:
  secretName: jamesmurphyx-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jamesmurphyx.net
  dnsNames:
    - jamesmurphyx.net
    - www.jamesmurphyx.net
